GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Test Blog 3",
    "author": "Test Author 3",
    "url": "http://test.com",
    "likes": 0
}
